In [3]:
import numpy as np
import pandas as pd

In [4]:
# создание массива
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
# все данные должны быть одного типа. Можно сразу задать, через dtype
arr1 = np.array([1,2,3], dtype = float)
arr1.dtype

dtype('float64')

In [6]:
# для создания многомерного массива:
arr2 = np.array([[1,1,1],[2,2,2],[3,3,3]])
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [7]:
# проверка формы массива
arr2.shape

(3, 3)

In [8]:
# образение к элементу двумерного массива по индексам
arr2[1,1]

2

In [9]:
# для выполнения математичекиз действий с количественными показателями из DF Pandas, их можно выгрузить в np.array
df = pd.DataFrame([[1,2,3],[2,2,2],[3,3,3]])
# с помощью функции values преобразовываем численые показатели в массив
x = df.values
type(x)
x

array([[1, 2, 3],
       [2, 2, 2],
       [3, 3, 3]], dtype=int64)

In [10]:
# так же можно получить массив из Series

s = pd.Series([1,2,3])
s.values

array([1, 2, 3], dtype=int64)

In [40]:
# иногда для решения какой либо задачи требуется заранее создать массив заданного размера. 
# Для этого используются специальные функции, заполняющие массив нулями или единицами

# np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

# np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

# np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

# np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

# np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

# np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

# np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

# массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)
# np.random.randint(0, 10, (3, 3))  

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
np.arange(1, 14, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [13]:
# обращение по индексу к элементам одномерных массивов
my_array = np.array([x for x in range(10)])
my_array[5] #элемент массива с индексом 5
my_array[-1] #первый с конца элемент массива
my_array[3:6] #срез с 3 по 6 элементы
my_array[1:8:3] #срез с 1 по 8 с шагом 3


array([1, 4, 7])

In [35]:
# обращение по индексу к элементам двумерных массивов
my_array = np.array([[x for x in range(10)],[x for x in range(10,20)]])
print(my_array)
my_array[1][2]
my_array[1,2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


12

In [33]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48]])
my_array[:3]
# array([[ 1,  2,  3,  4],
#        [10, 11, 12, 13],
#        [45, 46, 47, 48]])

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [ ]:
# задание 9.3

first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

big_secret
  
# # 1. Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

# last_list = []
# for i in range(0,5):
#     print(big_secret[i][-1])
#     last_list.append(big_secret[i][-1])
# sum(last_list) 


# 2. Выделите из каждой строки массива big_secret первые 5 элементов. 
# Чему равна сумма элементов главной диагонали получившейся матрицы? 
# Округлите ответ до двух цифр после запятой:
# count = 0
# for i in range(0,5):
#     print(big_secret[i][0:5])
#     count += big_secret[i][0:5][i]

# count
    
# 3. Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? 
# Введите полученный результат без изменений и округлений.

# count = 1
# for i in range(0,5):
#     print(big_secret[i][-5:])
#     count *= big_secret[i][-5:][i]

# count
   




In [17]:
              # Функции добавления элементов в массив

import numpy as np
a = np.array([1, 2, 3, 4]) 

# добавление элемента в конец массива
np.append(a, 0)
# array([1, 2, 3, 4, 0]) результат

# добавление нескольких элементов в конец массива
np.append(a, [5, 6, 7, 8, 9])
# # array([1, 2, 3, 4, 5, 6, 7, 8, 9]) результат
 

b = np.array([[2, 3], [5, 7]]) #двумерный массив

# добавление элемента в двумерный массив
np.append(b, [[11, 13]], axis = 0)
# # array([[ 2,  3], #результат
# #        [ 5,  7],
# #        [11, 13]])

# np.append(b, [[11, 13]], axis = 1)     #  Приведет к ошибке
 
# #  Ошибка вызвана тем что формы массивов должны 
# ... #  совпадать по всем осям, кроме той, что указана в axis:
# # ... b.shape, np.array([[11, 13]]).shape
# # ((2, 2), (1, 2))

# np.append(b, [[11], [13]], axis = 1)
# # array([[ 2,  3, 11],
# #        [ 5,  7, 13]])

# np.append(b, [[11, 17], [13, 19]], axis = 1)
# # array([[ 2,  3, 11, 17],
# #        [ 5,  7, 13, 19]])

# np.append(b, [[11, 17, 23], [13, 19, 29]], axis = 1)
# # array([[ 2,  3, 11, 17, 23],
# #        [ 5,  7, 13, 19, 29]])

array([[ 2,  3],
       [ 5,  7],
       [11, 13]])

In [44]:
# изменение среза массива вносит изменение в сам массив, двже если срез сделан отдельной переменной
my_array = np.random.randint(1,100,(4,6))
my_slice = my_array[1:3,2:4]
# my_slice
my_slice[:] = 0
my_array

array([[ 5, 86],
       [52, 39]])

In [19]:
# задания

first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])


# print(len(big_secret[0]))

# Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.
for i in range(0,5):
    for y in range(len(big_secret[i])):
#         print(big_secret[i, y])
#         print(i,y)
        if i%2 == 0 and y%2 == 0:
            big_secret[i,y] = -1
        elif i%2 != 0 and y%2 != 0:
            big_secret[i,y] = 1
        else:
            pass

big_secret

# 1. Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. 
# Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений.

# count = 0
# for i in range(0,5):
#     print(big_secret[i][0:5])
#     count += big_secret[i][0:5][i]

# count

# 2. Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. 
# Чему равно произведение элементов главной диагонали получившейся матрицы? 
# Введите полученный результат без изменений.

count = 1
for i in range(0,5):
    print(big_secret[i][-5:])
    count *= big_secret[i][-5:][i]

count


[ -1. 276.  -1. 490.  -1.]
[33.04542328  1.         33.10589071  1.         33.1662479 ]
[-1.000e+00  2.209e+03 -1.000e+00  2.401e+03 -1.000e+00]
[33.04542328  1.         33.10589071  1.         33.1662479 ]
[ -1. 276.  -1. 490.  -1.]


-1.0

In [20]:
                        # методы и функции применяемые к массивам
# транспонирование
arr = np.array([[1,1,1,1],[2,2,2,2]]).T
arr

# изменение размерности массива
arr = np.random.randint(0,10,10)
arr
arr.reshape((5,2))

# преобразование многомерного массива в одномерный
arr = np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3,]])
arr
arr.flatten()

# функции сравнения и выделения нужных элементов по условию
arr = np.random.randint(0,10,(3,4))

arr<5 # заполнения массива булевыми значениями соответствия условию
arr[arr<5] #

# маска используется для выбора определенных столбцов или строк и сокрытия всего остального
mask = np.array([1, 0, 1, 0], dtype=bool)
arr[:, mask]

# сортировка двумерных массивов
arr = np.random.randint(1,10,(3,10))
np.sort(arr, axis = 0) # axis = 0 используется для столбцов
np.sort(arr, axis = 1) # axis = 1 используется для строк

array([[1, 2, 2, 3, 6, 6, 8, 8, 8, 9],
       [1, 2, 2, 3, 5, 5, 7, 7, 8, 9],
       [1, 2, 2, 3, 4, 4, 4, 5, 8, 9]])

In [21]:
# Упражнения 9.4

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
# 1. Сколько столбцов содержит массив great_secret?

# 2. Чему равна сумма косинусов первой строки
sum(np.cos(great_secret[0]))

# 3. Чему равна сумма элементов массива great_secret, значение которых больше 50?
sum(great_secret[great_secret>50])

# 4. Переведите массив great_secret в одномерную форму. 
# Какое значение в получившемся массиве имеет элемент с индексом 150? 

great_secret.flatten()[150]

# 5. Отсортируйте значения столбцов массива great_secret по возрастанию. 
# Чему равна сумма элементов последней строки отсортированного массива? 

sort = np.sort(great_secret, axis = 0)

sum(sort[len(sort)-1])
#  9.94987437,  5.83827246, 99.33333333]

115.12148016521353

In [22]:
f = pd.DataFrame({'id':['1','2','3','4','5','6','7','8','9','10'],
                  'Рост':['135','160','163','147','138','149','136','154','137','165'],
                  'Масса тела': ['34','43','40','44','41','54','39','48','35','60'],
                  'Средний балл':['4','5','4.3','5','4.7','3.9','4.2','4.9','3.7','4.6']})

students = np.array(df, dtype = float)
f

id Рост Масса тела Средний балл
0   1  135         34            4
1   2  160         43            5
2   3  163         40          4.3
3   4  147         44            5
4   5  138         41          4.7
5   6  149         54          3.9
6   7  136         39          4.2
7   8  154         48          4.9
8   9  137         35          3.7
9  10  165         60          4.6

In [23]:

df = pd.DataFrame({'id':['1','2','3','4','5','6','7','8','9','10'],
                  'Рост':['135','160','163','147','138','149','136','154','137','165'],
                  'Масса тела': ['34','43','40','44','41','54','39','48','35','60'],
                  'Средний балл':['4','5','4.3','5','4.7','3.9','4.2','4.9','3.7','4.6']})

students = np.array(df, dtype = float)

# students[:,-1] #срез последнего столблца

# среднее значение успеваемости учеников
# np.mean(students[:,-1])
# 4.430000000000001

# значение медианы успеваемости
np.median(students[:,-1])
# 4.449999999999999

# задания
# чему равно медианное значение массы тела
np.median(students[:,-2])

# На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? 
# Дайте ответ в килограммах с точностью до одной десятой кг.

abs(np.median(students[:,-2]) - np.mean(students[:,-2]))

1.7999999999999972

In [24]:
# коэффициент корреляции для массы и роста

np.corrcoef(students[:,1], students[:,2])

# задание

# 1. Между какой парой признаков в массиве students наблюдается минимальная корреляция?

np.corrcoef(students[:,2], students[:,3])


array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [25]:
np.std(students[:,1])

11.083320801997928

In [29]:
# Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.
np.std(students[:,3])

# Посчитайте, чему равна дисперсия значений веса школьников.
np.var(students[:,2])

60.36

In [141]:
1. # Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, 
# с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_slice = my_array[1:4,1:4]

2. # Создайте массив my_sin, состоящий из синусов элементов массива my_array. 
# Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после запятой.

# my_sin= np.sin(my_array)
# sum(my_sin.flatten())

3. # Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.
# Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

my_sin = np.sin(my_array)
my_sin
my_slice = my_sin[1:4,1:4]

my_slice[:] = 1
my_sin
sum(my_sin.flatten())

4. # Преобразуйте первые 4 столбца массива my_sin в массив из 10 строк и 2 столбцов. 
# Чему равна сумма элементов первого столбца получившегося массива? 
# Ответ округлите до трёх заков после запятой.

arr1 = np.sin(my_array)
my_slice = arr1[1:4,1:4]
my_slice[:] = 1
slice_arr = arr1[:,:4]
slice_arr
slice_arr.reshape((10,2))[:,0]
sum(slice_arr.reshape((10,2))[:,0])


2.4057172058139544

In [158]:
# Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

bigdata = np.array([x**2 for x in range(100,1000) if x%2 !=0] , dtype = int)

#чему равна медиана
np.median(bigdata)

# чему равно стандартное отклонение
np.std(bigdata)

# Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами? 
# Введите полученный ответ без изменений и округлений.

bigdata.flatten()

list1 = []
list2 = []
for x in range(len(bigdata)):
    if x%2 == 0:
        list1.append(bigdata[x])
    else:
        list2.append(bigdata[x])

arr1 = np.array([list1])
arr2 = np.array([list2])

np.corrcoef(arr1,arr2)

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])