In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [20]:
df.columns = ['rent','area','rooms','floor','demo','liv_area']
df

rent  area  rooms  floor  demo  liv_area
0    65    50      3      5     8        37
1    70    52      2     12     4        40
2   120    80      1     10     5        65
3    35    33      1      3    10        20
4    40    33      1      6    20        16
5    50    44      2     13    12        35
6   100    80      4      8     5        60
7    90    65      3     21     1        50
8    85    65      2      5    10        40

Найдите вектор параметров квартиры номер 5:

In [17]:
np.array(df.loc[4])

array([40, 33,  1,  6, 20, 16], dtype=int64)

Найдите вектор этажей всех квартир:

In [19]:
np.array(df.floor)

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

На каком этаже расположена квартира номер 3?

In [22]:
df.loc[2]

rent        120
area         80
rooms         1
floor        10
demo          5
liv_area     65
Name: 2, dtype: int64

Найдите количество квартир:

In [28]:
df.rent.count()

9

Вычислите вектор нежилой площади:

In [30]:
np.array(df.area) - np.array(df.liv_area)

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны:

In [31]:
np.array(df.rent)/10 * 4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

In [32]:
df['time'] = [10,20,30,15,5,40,20,8,20]

In [33]:
df

rent  area  rooms  floor  demo  liv_area  time
0    65    50      3      5     8        37    10
1    70    52      2     12     4        40    20
2   120    80      1     10     5        65    30
3    35    33      1      3    10        20    15
4    40    33      1      6    20        16     5
5    50    44      2     13    12        35    40
6   100    80      4      8     5        60    20
7    90    65      3     21     1        50     8
8    85    65      2      5    10        40    20

In [35]:
np.linalg.norm(np.array(df.time)*14)

897.9665918061763

In [43]:
np.linalg.norm(np.array(df.time)@np.array(df.demo)) #попарное перемножение столбцов

1348.0

Проверьте, являются ли векторы попарно ортогональными

In [44]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [45]:
print(u@v)
print(u@w)
print(v@w)

0
0
0


In [47]:
Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

SyntaxError: invalid syntax (<ipython-input-47-e740b7724b81>, line 1)

In [49]:
comb = v*2+w*(-3)

Будет ли эта комбинация ортогональна вектору \(u\)?

In [50]:
print(u@comb)

0


Нормируйте векторы \(u, v, w\).

In [51]:
print(v/np.linalg.norm(v))
print(u/np.linalg.norm(u))
print(w/np.linalg.norm(w))

[ 0.          0.33333333  0.          0.66666667 -0.66666667]
[0.8660254  0.         0.28867513 0.28867513 0.28867513]
[ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]
