In [2]:
import numpy as np

Hus = np.array([100,220,140])
Wife = np.array([150,200,130])
Mother = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])


Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.

In [6]:
inc = np.matrix([Hus,Wife,Mother])
inc

matrix([[100, 220, 140],
        [150, 200, 130],
        [ 90,  80, 100]])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

In [8]:
cons = np.matrix([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption])
cons

matrix([[ 50,  50,  60],
        [100,  80, 140],
        [100,  20, 140]])

In [11]:
taxes = np.matrix([Hus*0.87,Wife*0.87,Mother*0.87])
taxes

matrix([[ 87. , 191.4, 121.8],
        [130.5, 174. , 113.1],
        [ 78.3,  69.6,  87. ]])

In [12]:
taxes-cons

matrix([[ 37. , 141.4,  61.8],
        [ 30.5,  94. , -26.9],
        [-21.7,  49.6, -53. ]])

In [20]:
A = np.matrix([[1,-1,2,4,0],[8,2,0,5,3],[0,1,2,1,2]])
B = np.matrix([[1,0,1,0],[0,0,2,-1],[1,0,1,1],[0,1,1,1],[1,1,0,-1]])
C = A*B
C[2,3]

0

In [40]:
a = np.matrix([1,3])
b = np.matrix([-3,1])
print(a,b)
a.T

[[1 3]] [[-3  1]]


matrix([[1],
        [3]])

In [39]:
np.dot(a.T,b)

matrix([[-3,  1],
        [-9,  3]])

In [43]:
a = np.matrix([[2,0],[0,3]])
b = np.matrix([[1,1],[4,5]])
a

matrix([[2, 0],
        [0, 3]])

In [44]:
a*b

matrix([[ 2,  2],
        [12, 15]])

In [45]:
b*a

matrix([[ 2,  3],
        [ 8, 15]])

In [64]:
a = np.array([1,1])
b = np.array([2,-1])
c = np.array([1,2])

In [65]:
all = np.matrix([a,b,c])
all

matrix([[ 1,  1],
        [ 2, -1],
        [ 1,  2]])

In [66]:
all*all.T

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])

In [71]:
(np.linalg.norm(c))**2

5.000000000000001

Найдите произведение матрицы  и вектора  в том порядке, в котором их можно умножить.

In [72]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [78]:
A@x

array([26, 30])

Найдите произведение матриц  и  в том порядке, в котором их можно умножить.

In [80]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
A

array([[1, 9, 8, 5],
       [3, 6, 3, 2],
       [3, 3, 3, 3],
       [0, 2, 5, 9],
       [4, 4, 1, 2]])

In [88]:
C = np.dot(B,A)
C[0,3]

14

Найдите матрицу Грама системы векторов 

In [89]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [90]:
G = np.matrix([x,y,z])

In [91]:
G*G.T

matrix([[22,  3,  0],
        [ 3,  7,  0],
        [ 0,  0,  3]])

В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [93]:
import pandas as pd
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

Найдите вектор выручки Бориса.

In [95]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [96]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [102]:
Count_DF.loc['Борис']*Price_DF.loc['Борис']

Женские стрижки     3.6
Мужские стрижки    52.5
Окрашивания         3.0
Укладка            25.0
Уход                6.0
Name: Борис, dtype: float64

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [103]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]

In [125]:
salon_inc = ((Count_DF*Price_DF))@com

salon_inc

Аня      11.30
Борис    15.22
Вика     11.90
Галя     20.60
Дима     41.90
Егор     21.20
Женя     11.49
Юра      38.25
dtype: float64

In [112]:
salon_inc

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               4.00             1.50         3.60     1.20   1.0
Борис             0.72            10.50         0.90     2.50   0.6
Вика              4.80             4.80         0.00     1.50   0.8
Галя              1.44             1.92        15.12     1.12   1.0
Дима              3.00            17.50        16.20     2.50   2.7
Егор             10.00             3.00         1.80     3.40   3.0
Женя              4.84             0.20         1.80     1.25   3.4
Юра               6.30             0.00        23.25     3.10   5.6

In [127]:
inc = []
for i in salon_inc.index:
    inc.append(salon_inc.loc[i].sum())
np.array(inc)


array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [123]:
salon_inc.loc['Борис'].sum()

15.22

In [133]:
inc = []

all = ((Count_DF*Price_DF))@(np.ones(5)-com) #создаем единичный вектор и из него вычитаем процент
print(all)
for i in all.index:
    inc.append(all.loc[i].sum())
np.array(inc)

Аня       50.20
Борис     74.88
Вика      59.10
Галя      67.80
Дима     166.60
Егор     113.80
Женя      66.21
Юра      157.75
dtype: float64


array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

обратная матрица

In [138]:
A = np.matrix('1,2;2,5')
A

matrix([[1, 2],
        [2, 5]])

In [137]:
np.linalg.inv(A)

matrix([[ 5., -2.],
        [-2.,  1.]])

In [2]:
A = np.matrix('2,0,0;0,1,0;0,0,4')

In [10]:
A
B = np.linalg.inv(A)
B 

matrix([[0.5 , 0.  , 0.  ],
        [0.  , 1.  , 0.  ],
        [0.  , 0.  , 0.25]])

In [9]:
B

matrix([[2, 0, 0],
        [0, 1, 0],
        [0, 0, 4]])

In [11]:
np.linalg.det(B)

0.12500000000000003

Найдите обратную матрицу к матрице А.

In [3]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [13]:
B = np.linalg.inv(A)
B[1][0]


0.375

Найдите ранг системы векторов v1, v2, v3, v4.

In [14]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [28]:
A = np.array([v1,v2,v3,v4])
np.linalg.matrix_rank(A)

4

In [30]:
A[0][3]

7

Найдите матрицу Грама системы векторов v1, v2, v3, v4.

In [35]:
B = A@A.T
B

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

Найдите определитель матрицы Грама системы v1, v2, v3, v4.

In [34]:
np.linalg.det(B)

3716647.9999999995

Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4.

In [38]:
C = np.linalg.inv(B)
round((C[2][0]), 3)

-0.026