In [1]:
import numpy as np


создание матрицы

In [19]:
A = np.array([[1,-5,3],[2,2,1],[0,3,1],[2,4,12]])
type(A)

numpy.ndarray

In [6]:
 A.shape #форма

(4, 3)

In [9]:
A.reshape(2,6) #изменение формы

array([[ 1, -5,  3,  2,  2,  1],
       [ 0,  3,  1,  2,  4, 12]])

In [13]:
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [16]:
A[1,1]

2

In [18]:
A.T #ранспонирование матрицы


array([[ 1,  2,  0,  2],
       [-5,  2,  3,  4],
       [ 3,  1,  1, 12]])