In [1]:
import numpy as np

ниже представлен вектор, как последовательность чисел - параметров квартиры. Сами числа - признаки

На рынке новостроек появилось предложение от застройщика "Гарантия" — двухкомнатная квартира общей площадью  59.5 кв.м, жилой площадью 31.4 кв.м на 19-м этаже 22-х этажного дома. В доме 2 подъезда. Цена за квадратный метр квартиры у этого застройщика составляет 60550 рублей.




In [20]:
apartment = np.array([59.50,31.40,19,2,60550,2])


Давайте, как настоящие исследователи данных, попробуем извлечь полезную информацию из вектора, при этом уменьшив его! 

Упростим себе задачу оценки новой квартиры — сгенерируем новый признак — отношение жилой площади к общей. А от старых признаков смело избавимся, сократив векторное пространство нашего объекта.

Возьмём квартиру из описания выше и представим её неким вектором apartment:

Для того, чтобы сгенерировать новый параметр share_living_space (доля жилой площади в квартире) из старых признаков, содержащихся в векторе-описании apartment нашей квартиры, нам необходимо вспомнить обращение к элементам массива. Разделим значение жилой площади на её общее количество:

In [21]:
share_living_space = apartment[1]/apartment[0]
share_living_space

0.5277310924369748

Избавимся от старых признаков, посредством функции delete(), которую предоставляет библиотека numpy. Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment:

И добавим новый признак в конец массива

In [22]:
apartment = np.delete(apartment, [0, 1])
apartment

array([1.900e+01, 2.000e+00, 6.055e+04, 2.000e+00])

In [23]:
apartment = np.append(apartment, share_living_space)

In [24]:
apartment

array([1.90000000e+01, 2.00000000e+00, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

Размерность массива

In [32]:
len(apartment)

5

Пусть дан вектор в python вида t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13]), содержащий информацию о средней температуре воздуха (в градусах Цельсия) в Риме с января по декабрь включительно.

Выберите неверное утверждение:

In [33]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

In [36]:
t[5]

28

Задания


In [38]:
x = np.array([120,150,90])
y = np.array([130,130,130])
z = np.array([2,3,2.5])
e = 72
z= z*e
x+y+z

array([394., 496., 400.])