In [1]:
import numpy as np

In [2]:
A = np.matrix('4,7;5,10')
b = np.matrix('20,30')

In [13]:
(np.linalg.inv(A))*b.T

matrix([[-2.],
        [ 4.]])

In [32]:
A = np.matrix('4,7,1;-4,2,5;0,9,4')
b = np.matrix('7,3,10')

In [33]:
A|b

matrix([[ 7,  7, 11],
        [-1,  3, 15],
        [ 7, 11, 14]], dtype=int32)

In [34]:
np.linalg.matrix_rank(A)

3

In [35]:
np.linalg.matrix_rank(A|b)

3

Вычислите вектор ошибок для приближённого решения системы w, если

In [51]:
A = np.matrix('1,-5;2,1;1,1')
w = np.matrix('1,1')
b = np.matrix('1,2,2')
print(A.T)
print(w.T)
print(b)

[[ 1  2  1]
 [-5  1  1]]
[[1]
 [1]]
[[1 2 2]]


In [56]:
b.T - A*w.T

matrix([[ 5],
        [-1],
        [ 0]])

Найдите OLS оценку для коэффициентов w1, w2 СЛАУ

In [12]:
A = np.matrix('1,2;-3,1;1,2;1,-1')
b = np.matrix('1,4,5,0')
print(b)
print(A.T)

[[1 4 5 0]]
[[ 1 -3  1  1]
 [ 2  1  2 -1]]


In [4]:
A.T*A

matrix([[12,  0],
        [ 0, 10]])

In [14]:
A_inv = np.linalg.inv(A.T*A)

In [17]:
b_w = A.T*b.T

In [20]:
A_inv.T*b_w

matrix([[-0.5],
        [ 1.6]])

In [21]:
-29.3-0.26*0.2+8.4*6

21.048000000000005